# Generated by Django 3.2.5 on 2021-07-05 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_recipe'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Recipe',
        ),
    ]
