# Generated by Django 3.2.5 on 2021-07-05 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=600)),
                ('subtitle', models.CharField(max_length=600)),
                ('intro', models.CharField(max_length=600)),
                ('steps', models.CharField(max_length=600)),
                ('summary', models.CharField(max_length=600)),
                ('likes', models.JSONField()),
                ('comments', models.JSONField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipies', to='recipies.author')),
            ],
        ),
    ]
