# Generated by Django 3.2.5 on 2021-07-05 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='about',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
