# Generated by Django 3.2.5 on 2021-07-05 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipies', '0002_author_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='comments',
            field=models.JSONField(blank=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='likes',
            field=models.JSONField(blank=True),
        ),
    ]
