# Generated by Django 3.2.5 on 2021-07-05 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipies', '0003_auto_20210705_1923'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='likes',
        ),
    ]
