# Generated by Django 3.2.5 on 2021-07-05 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipies', '0004_auto_20210705_1924'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Author',
            new_name='Chef',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='author',
            new_name='chef',
        ),
    ]
